# data structures: provisionary directory for when I start CRLS
CC = gcc
CFLAGS = -Wall -Wextra -Werror -O3 -std=c99 -pedantic

xor-linked-list: xor-linked-list.c
	${CC} ${CFLAGS} -o xor-linked-list xor-linked-list.c

clean:
	rm -f xor-linked-list
